[workspace]
members = ["core", "macros"]

[package]
name = "vy"
version = "0.2.0"
edition = "2021"

[features]
default = ["std"]
std = ["vy-core/either"]
either = ["vy-core/either"]

[dependencies]
vy-core = { path = "./core", version = "0.2.0" }
vy-macros = { path = "./macros", version = "0.2.0" }
