[workspace]
members = ["macros"]

[package]
name = "vy"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = []

[dependencies]
vy-macros = { version = "0.1.0", path = "macros" }
ryu = "1"
itoap = "1"
