[workspace]
resolver = "2"
members = ["core", "macros"]

[package]
name = "vy"
version = "0.2.0"
edition = "2021"

[dependencies]
vy-core = { path = "./core", version = "0.2.0" }
vy-macros = { path = "./macros", version = "0.2.0" }
