[workspace]
members = ["macros", "runtime"]

[package]
name = "vy"
version = "0.2.0"
edition = "2021"
authors = ["Jonah Lund <jonahlund@proton.me>"]
description = "Fast and minimal HTML templating macros in Rust"
repository = "https://github.com/JonahLund/vy"
keywords = ["html", "macros", "template"]
categories = ["template-engine", "web-programming"]
license = "MIT"
rust-version = "1.70"

[features]
std = []
default = ["std"]

[dependencies]
vy-macros = { git = "https://github.com/jonahlund/vy-macros", branch = "v0.2.0" }
vy-runtime = { git = "https://github.com/jonahlund/vy-runtime", branch = "v0.2.0" }
