[package]
name = "vy"
version = "0.1.0"
edition = "2021"

[features]
default = ["alloc", "std"]
alloc = []
std = []

[dependencies]
vy-macros = { version = "0.1.0", path = "../vy-macros" }
itoa = "1"
ryu = "1"
