[package]
name = "vy-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
tiny-rsx = { version = "0.2.0", path = "../../tiny-rsx" }
proc-macro2 = "1"
quote = "1"
syn = "2"
