[package]
name = "vy-core"
version = "0.2.0"
edition = "2021"
license = "MIT"
workspace = "../"

[features]
std = []

[dependencies]
itoap = "1.0.1"
ryu = "1"

[dev-dependencies]
vy = { path = "../" }
