[package]
name = "vy-macros"
version = "0.1.0"
edition = "2021"
authors = ["Jonah Lund <jonahlund@proton.me>"]
description = "Fast and minimal HTML templating macros in Rust"
repository = "https://github.com/JonahLund/vy"
license = "MIT"
rust-version = "1.70"

[lib]
proc-macro = true

[dependencies]
vy-core = { version = "0.1.0", path = "../core" }
tiny-rsx = "0.3.0"
proc-macro2 = "1"
quote = "1"
syn = "2"
