[package]
name = "vy-macros"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
vy-core = { path = "../core", version = "0.2.0" }
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = "2.0.98"
tiny-rsx = { git = "https://github.com/jonahlund/tiny-rsx.git", branch = "v0.4.0" }
