name: Continuous Integration

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Execute tests
        run: cargo test --workspace --all-features --all-targets

      - name: Test docs
        run: cargo test --doc

  check:
    name: Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check code
        run: cargo clippy --all-features --all-targets -- -D warnings

  format:
    name: Format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rustdoc
        run: cargo rustdoc --all-features -- -D warnings

  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check typos
        uses: crate-ci/typos@master
        with:
          files: .

  cargo_sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-sort
        run: cargo install --locked cargo-sort

      - name: Check sorting
        run: cargo sort -c

  machete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stable Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install `cargo-machete`
        run: cargo install --locked cargo-machete

      - name: Check unused dependencies
        run: cargo machete
